#define WIN_WIDTH 512
#define WIN_HEIGHT 512

#define IMAGE_WIDTH 5.0

#define STOCHASTIC_RAY_COUNT 5
#define OCTTREE_SPLIT_STEP 1

#define OCT_OUTPUT
//#define OCT_REDUCE_MEM
#define SHOW_PROGRESS

#define GT_PARALLEL